root: true
env:
  es6: true
extends: eslint:recommended
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
overrides:
  - files:
    - '**/*.test.js'
    - '**/*.test.mjs'
    extends: plugin:jest/recommended
  - files:
    - "*.js"
    env:
      es6: false
      node: true
